package com.shiyu.sime.ime.data;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Emoji data store parsed from {@code emoji.txt} (generated by
 * {@code pipeline/gen_emoji.py}). Groups are delimited by
 * {@code # group: <label>} lines; all other lines are emoji characters.
 */
public class EmojiStore {

    private final List<String> labels = new ArrayList<>();
    private final List<List<String>> groups = new ArrayList<>();

    public void load(File emojiTxt) {
        if (emojiTxt == null || !emojiTxt.exists()) return;
        try (BufferedReader br = new BufferedReader(
                new InputStreamReader(new FileInputStream(emojiTxt), "UTF-8"))) {
            List<String> current = null;
            String line;
            while ((line = br.readLine()) != null) {
                if (line.startsWith("# group: ")) {
                    String label = line.substring("# group: ".length()).trim();
                    current = new ArrayList<>();
                    labels.add(label);
                    groups.add(current);
                } else if (!line.isEmpty() && current != null) {
                    current.add(line.trim());
                }
            }
        } catch (Exception e) {
            // Silently degrade to empty.
        }
    }

    /** Category labels in display order. */
    public List<String> labels() {
        return Collections.unmodifiableList(labels);
    }

    /** Emojis for the category at {@code index}. */
    public List<String> emojis(int index) {
        if (index < 0 || index >= groups.size()) return Collections.emptyList();
        return Collections.unmodifiableList(groups.get(index));
    }
}
